
### register user
POST http://localhost:5500/api/v1/users/register
Content-Type: application/json

{
    "Username": "NGENO" ,
    "Email": "NGENO@gmail.com" ,
    "Password": "1234562@K",
    "TagName": "@rose",
    "Location": "Nyeri"
}

### Login user
POST http://localhost:5500/api/v1/users/login
Content-Type: application/json

{
    "Email": "NGENO@gmail.com",
    "Password": "1234562@K"
}


### update user
PUT http://localhost:5500/api/v1/users/update/017e6d02-567c-42de-9feb-b58a9e7fba4a
Content-Type: application/json

{
    "Username":"Leah25" ,
    "TagName":"@leah2",
    "Location":"Nyeri2"
}


### update the user password
PATCH http://localhost:5500/api/v1/users/patch/ba4abf58-33e5-4901-b528-bf7bbd55ffd0
Content-Type: application/json

{
    "Password": "123456@Ia"
}



### Fetching/getting all users
GET http://localhost:5500/api/v1/users/



### Fetching/getting single user
GET http://localhost:5500/api/v1/users/single/a10d55f1-7053-485f-b9df-f8da39d59080



### Deleting a single user
DELETE  http://localhost:5500/api/v1/users/delete/a10d55f1-7053-485f-b9df-f8da39d59080



##****************************************************POST**************************************************************##

### create a post
POST http://localhost:5500/api/v1/posts
Content-Type: application/json

{
    "UserID": "ba4abf58-33e5-4901-b528-bf7bbd55ffd0" ,
    "Content": "This is cool place loving it" ,
    "Likes": 10,
    "Comments": 5
}

### updating a single post
PUT http://localhost:5500/api/v1/posts/update/372cb816-52a8-4afb-8b12-37e69bd1ba2a
Content-Type: application/json

{
     "Content": "This is cool place loving it" ,
    "Likes": 5,
    "Comments": 6
}


### updating only the text
PATCH http://localhost:5500/api/v1/posts/patch/b28a2524-3d59-4334-9878-bd28efec9696
Content-Type: application/json

{
     "Content": "I new am loving this"
}

### Fetching/getting all posts
GET http://localhost:5500/api/v1/user/posts/9c402dd7-6623-4689-b4c2-f8529a3d0edc



### Fetching/getting all posts
GET http://localhost:5500/api/v1/posts/



### Fetching/getting single post
GET http://localhost:5500/api/v1/posts/single/9c402dd7-6623-4689-b4c2-f8529a3d0edc



### Deleting a single post
DELETE  http://localhost:5500/api/v1/posts/delete/372cb816-52a8-4afb-8b12-37e69bd1ba2a





##****************************************************Comment**************************************************************##

### create a comment
POST http://localhost:5500/api/v1/comments
Content-Type: application/json

{
    "UserID": "017e6d02-567c-42de-9feb-b58a9e7fba4a" ,
    "PostID": "b28a2524-3d59-4334-9878-bd28efec9696" ,
    "Content": "What a bad week" 
}

### updating a single comment
PUT http://localhost:5500/api/v1/comments/update/a0423f0f-ad07-4f2b-bfa5-a937e44dedf7
Content-Type: application/json

{
     "Content": "I am loving this" 
}


### updating only the text
PATCH http://localhost:5500/api/v1/comments/patch/a0423f0f-ad07-4f2b-bfa5-a937e44dedf7
Content-Type: application/json

{
     "Content": "I new am loving this"
}

### Fetching/getting all comments
GET http://localhost:5500/api/v1/comments/



### Fetching/getting single comment
GET http://localhost:5500/api/v1/comments/single/a0423f0f-ad07-4f2b-bfa5-a937e44dedf7



### Deleting a single comment
DELETE  http://localhost:5500/api/v1/posts/delete/372cb816-52a8-4afb-8b12-37e69bd1ba2a






##****************************************************PHOTOS**************************************************************##



### upload a photo
POST http://localhost:5500/api/v1/photos
Content-Type: application/json

{
    "UserID": "017e6d02-567c-42de-9feb-b58a9e7fba4a" ,
    "PhotoURL": "https://www.pexels.com/photo/a-bunch-of-flowers-in-buckets-and-bags-20079575/"
}



### updating a single photo
PUT http://localhost:5500/api/v1/photos/update/3352e56e-807b-4042-94c4-aafee75c1d68
Content-Type: application/json

{
    "PhotoURL": "https://images.pexels.com/photos/13991574/pexels-photo-13991574.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load"

}



### updating only the text
PATCH http://localhost:5500/api/v1/photos/patch/b90ca026-3b8e-4605-8a54-e89422a87c82
Content-Type: application/json

{
    "PhotoURL": "https://images.pexels.com/photos/13991574/pexels-photo-13991574.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load"

}



### Fetching/getting all photos
GET http://localhost:5500/api/v1/photos/



### Fetching/getting single photo
GET http://localhost:5500/api/v1/photos/single/3352e56e-807b-4042-94c4-aafee75c1d68



### Deleting a single photo
DELETE  http://localhost:5500/api/v1/photos/delete/3352e56e-807b-4042-94c4-aafee75c1d68




##****************************************************GROUPS**************************************************************##

### create a group
POST http://localhost:5500/api/v1/groups
Content-Type: application/json

{
    "GroupName": "Group A" ,
    "Description": "This is one of the best groups" 
}

### updating a single group
PUT http://localhost:5500/api/v1/groups/update/7d554ca6-2283-4755-b48e-1f316bb540de
Content-Type: application/json

{
    "GroupName": "Group c" ,
    "Description": "This is one of the best groups"
}

### updating only the text
PATCH http://localhost:5500/api/v1/groups/patch/7d554ca6-2283-4755-b48e-1f316bb540de
Content-Type: application/json

{
    "GroupName": "Group B" 
}



### Fetching/getting all groups
GET http://localhost:5500/api/v1/groups/


### Fetching/getting single group
GET http://localhost:5500/api/v1/groups/single/7d554ca6-2283-4755-b48e-1f316bb540de

### Deleting a single group
DELETE  http://localhost:5500/api/v1/groups/delete/7d554ca6-2283-4755-b48e-1f316bb540de




##****************************************************GROUPSMEMBERS**************************************************************##

### create a GROUPSMEMBERS
POST http://localhost:5500/api/v1/members
Content-Type: application/json

{
    "GroupID": "42db9bca-a1ad-45fa-b364-aa0910b98fdb" ,
    "MemberID": "017e6d02-567c-42de-9feb-b58a9e7fba4a" 
}



### Fetching/getting all groups
GET http://localhost:5500/api/v1/members/


### Fetching/getting single group
GET http://localhost:5500/api/v1/members/single/42db9bca-a1ad-45fa-b364-aa0910b98fdb

### Deleting a single group
DELETE  http://localhost:5500/api/v1/members/delete/7d554ca6-2283-4755-b48e-1f316bb540de



##****************************************************EVENTS**************************************************************##

### create an event
POST http://localhost:5500/api/v1/events
Content-Type: application/json

{
    "EventName": "Diani Tours" ,
    "EventPosterURL": "https://www.pexels.com/photo/a-bunch-of-flowers-in-buckets-and-bags-20079575/" ,
    "Description": "This will take place next month",
    "Location": "Nyeri",
    "EventDate": "16/10/2023"
}

### updating a single event
PUT http://localhost:5500/api/v1/events/update/02dbb5f4-6e00-442b-a786-25dce8ed8e8b
Content-Type: application/json

{
    "EventPosterURL": "https://www.pexels.com/photo/a-bunch-of-flowers-in-buckets-and-bags-20079575/" ,
    "Description": "This will take place next week",
    "Location": "Diani",
    "EventDate": "20/2/2024"
}



### Fetching/getting all Events
GET http://localhost:5500/api/v1/events/


### Fetching/getting single event
GET http://localhost:5500/api/v1/events/single/02dbb5f4-6e00-442b-a786-25dce8ed8e8b

### Deleting a single event
DELETE  http://localhost:5500/api/v1/events/delete/02dbb5f4-6e00-442b-a786-25dce8ed8e8b

##*******************************************************************EventAtendees*******************************************

### user registering for an event
POST http://localhost:5500/api/v1/event/attendee
Content-Type: application/json

{
    "EventID": "02dbb5f4-6e00-442b-a786-25dce8ed8e8b" ,
    "AttendeeID": "017e6d02-567c-42de-9feb-b58a9e7fba4a" 
}

# ### updating a single event
# PUT http://localhost:5500/api/v1/events/update/02dbb5f4-6e00-442b-a786-25dce8ed8e8b
# Content-Type: application/json

# {
#     "EventPosterURL": "https://www.pexels.com/photo/a-bunch-of-flowers-in-buckets-and-bags-20079575/" ,
#     "Description": "This will take place next week",
#     "Location": "Diani",
#     "EventDate": "20/2/2024"
# }



### Fetching/getting all Events Attendee
GET http://localhost:5500/api/v1/event/attendee


### Fetching/getting single event
GET http://localhost:5500/api/v1/event/attendee/02dbb5f4-6e00-442b-a786-25dce8ed8e8b

### Deleting a single event attendee
DELETE  http://localhost:5500/api/v1/event/attendee/delete/02dbb5f4-6e00-442b-a786-25dce8ed8e8b



##****************************************************FRIENDSHIP**************************************************************##

### Become friends
POST http://localhost:5500/api/v1/friendships
Content-Type: application/json

{
    "User1ID": "88c681ad-1cc7-4b18-a777-70717283edce" ,
    "User2ID": "d7b11358-d5d7-4ae7-ae4e-ecfff851467b"
}

        
### updating a single friendship
PATCH http://localhost:5500/api/v1/friendships/patch/96e7428c-4de7-478e-884e-9e3bef8cad5a
Content-Type: application/json

{

}


### Fetching/getting all friends
GET http://localhost:5500/api/v1/friendships/


### Fetching/getting all individual user friends
GET http://localhost:5500/api/v1/user/friendships/88c681ad-1cc7-4b18-a777-70717283edce


### Fetching/getting single friendship
GET http://localhost:5500/api/v1/friendships/single/96e7428c-4de7-478e-884e-9e3bef8cad5a


### Deleting a single pfriend
DELETE  http://localhost:5500/api/v1/friendships/delete/2e804b63-8aba-4c68-b05e-7afece1efbb2


##****************************************************MESSAGES**************************************************************##

### create a message
POST http://localhost:5500/api/v1/messages
Content-Type: application/json

{
    "SenderID": "017e6d02-567c-42de-9feb-b58a9e7fba4a" ,
    "ReceiverID": "ba4abf58-33e5-4901-b528-bf7bbd55ffd0" ,
    "Content": "I am in Love with You"
}

### updating a single message
PUT http://localhost:5500/api/v1/messages/update/288d9bb4-06d9-4ebf-a05d-09098f3af541
Content-Type: application/json

{
    "Content": "Sorry i mean am in Love with Your cloth"
}



### Fetching/getting all messages
GET http://localhost:5500/api/v1/messages


### Fetching/getting single message
GET http://localhost:5500/api/v1/messages/single/288d9bb4-06d9-4ebf-a05d-09098f3af541

### Deleting a single message
DELETE  http://localhost:5500/api/v1/messags/delete/288d9bb4-06d9-4ebf-a05d-09098f3af541
